- name: Install AWS Python libraries
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
  - boto3
  - botocore

- name: Create ec2 instances
  amazon.aws.ec2_instance:
   name: "{{ item }}"
   instance_type: "{{ instance_type }}"
   image_id: "{{ ami_id }}"
   region: us-east-1
   security_group: "{{ sg_id }}"
   subnet_id: "{{ subnet_id }}"
  loop: "{{ instances }}"
  register: ec2_info